# -*- coding: utf-8 -*-
"""YOLO11(Custom Datset).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dUARc3p-VC0vfZVOJWB0TUtTc3HQP04p
"""

!pip install ultralytics #  installs the Ultralytics YOLO library for object detection
from ultralytics import YOLO #imports the YOLO class from the installed library.
model=YOLO('yolo11n.pt') #loads a YOLO model from the file 'yolo11n.pt'
print('XYZ') #for checking whether working/not

!unzip /content/YOLO11/data/valid.zip -d /content/YOLO11/data # extracts valid.zip into the /content/YOLO11/data folder

train_results=model.train( #starts the training process and stores the results in train_results
data = "/content/YOLO11/data/data.yaml", # path to yaml
epochs=5, #trains the model for 5 iterations over the dataset.
imgsz=640, #resizes images to 640x640 pixels for training as Resizing makes training and prediction faster and reduces memory usage on GPU or CPU.
device=0, # runs training on GPU
)

from ultralytics import YOLO

model = YOLO("/content/runs/detect/train3/weights/best.pt") #loads the trained YOLO model

# Perform object detection on an image
results = model("/content/YOLO11/test_images/1.jpeg", save=True) # runs object detection on the image and saves the result.
results[0].show() #results- stores the detection output, including bounding boxes and labels and show- displays the detected objects on the image.

from ultralytics import YOLO

# Load a model
model = YOLO("/content/runs/detect/train3/weights/best.pt")

# Perform object detection on an image
results = model("/content/YOLO11/test_images", save=True)